version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: mypli-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mypli
      MYSQL_USER: mypli_user
      MYSQL_PASSWORD: mypli_pass
    ports:
      - "3306:3306"
    volumes:
      - /mnt/mypli-data/mysql:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --init-connect='SET NAMES utf8mb4'

  redis:
    image: redis:7-alpine
    container_name: mypli-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "redis_password"]

  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: mypli-api
    restart: unless-stopped
    env_file:
      - ./apps/api/.env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      # Redis도 마찬가지로 서비스 이름 사용
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis_password # 비밀번호 쓰면 이거도
    depends_on:
      - db
      - redis
    ports:
      - "3000:3000"

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: mypli-web
    restart: unless-stopped
    depends_on:
      - api

  proxy:
    image: nginx:stable-alpine
    container_name: mypli_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:ro
    depends_on:
      - web
      - api
