server {
    listen 80;
    server_name mypli.ddns.net;  # 도메인 나중에 붙일 거면 여기 바꿔주면 됨

    location / {
        proxy_pass http://mypli-web:80;
        try_files $uri /index.html;
    }

    location /api/ {
        proxy_pass http://mypli-api:3000;
    }
}

server {
    listen 443;
    server_name mypli.ddns.net;  # 도메인 나중에 붙일 거면 여기 바꿔주면 됨

    ssl_certificate     /etc/letsencrypt/live/mypli.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mypli.ddns.net/privkey.pem;


    # React 정적 페이지 (web 컨테이너의 nginx:80)
    location / {
        proxy_pass http://mypli-web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        try_files $uri /index.html;
    }

    # API 요청은 /api → NestJS
    location /api/ {
        proxy_pass http://mypli-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
