server {
    listen 80;
    server_name mypli.ddns.net; 

    return 301 https://$host:7777$request_uri;
}

server {
    listen 443 ssl;
    server_name mypli.ddns.net;  

    ssl_certificate     /etc/letsencrypt/live/mypli.ddns.net/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/mypli.ddns.net/privkey.pem;

    # SSL 보안 설정 추가
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;


   # API 요청은 /api → NestJS (먼저 처리)
    location /api/ {
        proxy_pass http://mypli-api:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # React 정적 페이지 (web 컨테이너의 nginx:80)
    location / {
        proxy_pass http://mypli-web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
