server {
    listen       80;
    listen       [::]:80;
    server_name  _;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    # SPA 라우팅 핵심
    location / {
        try_files $uri $uri/ /index.html;
    }

    # (옵션) 정적 파일 캐싱, 404 등은 필요하면 추가
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
